//
//  StyleKit.h
//  BluetoothTank
//
//  Created by Robert Mannuzza on 7/13/15.
//  Copyright (c) 2015 Me . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>



@interface StyleKit : NSObject

// Colors
+ (UIColor*)pathWay;
+ (UIColor*)insideHandle;
+ (UIColor*)outSidePathWay;
+ (UIColor*)outSideHandle;

// Shadows
+ (NSShadow*)shadow;

// Drawing Methods
+ (void)drawJoyStickWithWindowWidth: (CGFloat)windowWidth windowHeight: (CGFloat)windowHeight throttleSpeed: (CGFloat)throttleSpeed;
+ (void)drawCompassWithAngle: (CGFloat)angle;
+ (void)drawDistanceMeter;

@end



@interface NSShadow (PaintCodeAdditions)

+ (instancetype)shadowWithColor: (UIColor*)color offset: (CGSize)offset blurRadius: (CGFloat)blurRadius;
- (void)set;

@end
