//
//  ThrottleImages.h
//  BluetoothTank
//
//  Created by Robert Mannuzza on 1/24/15.
//  Copyright (c) 2015 Me . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>



@interface ThrottleImages : NSObject

// Colors
+ (UIColor*)pathWay;
+ (UIColor*)insideHandle;
+ (UIColor*)outSidePathWay;
+ (UIColor*)outSideHandle;

// Shadows
+ (NSShadow*)shadow;

// Drawing Methods
+ (void)drawJoyStickWithHeight: (CGFloat)height windowHeight: (CGFloat)windowHeight;

@end



@interface NSShadow (PaintCodeAdditions)

+ (instancetype)shadowWithColor: (UIColor*)color offset: (CGSize)offset blurRadius: (CGFloat)blurRadius;
- (void)set;

@end
